name: Outputs syntax

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@main

      # Does or does not need an additional $(echo ...) ?
      - name: Create output
        id: test
        env:
          B2B: "bay-to-breaker"
        run: |
          echo "::set-output name=a::Anthropologie"
          echo "::set-output name=b::${B2B#*-}"
      
      - name: Check previous output
        run: |
          echo ${{ steps.test.outputs.a }}
          echo ${{ steps.test.outputs.b }}
